name: percona-server-mysql # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '8.0.32-24' # just for humans, typically '1.2+git' or '1.3.2'
summary: Percona Server for MySQL in a snap. # 79 char long summary
description: |
  The MySQL software delivers a very fast, multithreaded, multi-user,
  and robust SQL (Structured Query Language) database server. MySQL
  Server is intended for mission-critical, heavy-load production
  systems as well as for embedding into mass-deployed software.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

system-usernames:
  snap_daemon: shared

package-repositories:
  - type: apt
    components:
      - main
    suites:
      - jammy
    key-id: 4D1BB29D63D98E422B2113B19334A25F8507EFA5
    url: http://repo.percona.com/pdps-8.0.32/apt

layout:
  /var/lib/mysql-files:
    bind: $SNAP_COMMON/var/lib/mysql-files
  /usr/lib/mysqlrouter:
    symlink: $SNAP/usr/lib/mysqlrouter
  /usr/lib/mysql-router:
    symlink: $SNAP/usr/lib/mysql-router
  /etc/mysqlrouter:
    bind: $SNAP_DATA/etc/mysqlrouter
  /var/lib/mysqlrouter:
    bind: $SNAP_COMMON/var/lib/mysqlrouter
  /var/log/mysqlrouter:
    bind: $SNAP_COMMON/var/log/mysqlrouter
  /usr/lib/mysqlsh:
    bind: $SNAP/lib/mysqlsh


hooks:
  install:
    plugs:
      - network
      - network-bind
  configure:
    plugs:
      - network

slots:
  logs:
    interface: content
    source:
      read:
        - $SNAP_COMMON/var/log/mysql
  mysqlrouter-sockets:
    interface: content
    content: socket-directory
    write:
      - $SNAP_COMMON/var/run/mysqlrouter

apps:
  mysql:
    command: usr/bin/mysql
    plugs:
      - network
  mysqld:
    command: start-mysqld.sh
    daemon: simple
    install-mode: disable
    plugs:
      - network
      - network-bind
  mysqlsh:
    command: usr/bin/mysqlsh
    plugs:
      - network
  mysqlrouter:
    command: run-mysql-router.sh
    plugs:
      - network
  mysqlrouter-service:
    command: start-mysql-router.sh
    daemon: simple
    install-mode: disable
    plugs:
      - network
      - network-bind
  xtrabackup:
    command: usr/bin/xtrabackup
  xbcloud:
    command: usr/bin/xbcloud
    plugs:
      - network
  xbstream:
    command: usr/bin/xbstream
parts:
  pin-mysql-apt:
    plugin: nil
    override-pull: |
      printf "Package: percona-server-server\nPin: version 8.0.32*\nPin-Priority: 1001\n" > /etc/apt/preferences.d/mysql
      printf "\nPackage: percona-mysql-router\nPin: version 8.0.32*\nPin-Priority: 1001\n" >> /etc/apt/preferences.d/mysql
      printf "\nPackage: percona-xtrabackup-80\nPin: version 8.0.32*\nPin-Priority: 1001\n" >> /etc/apt/preferences.d/mysql
      printf "\nPackage: percona-mysql-shell\nPin: version 8.0.32*\nPin-Priority: 1001\n" >> /etc/apt/preferences.d/mysql
  packages-deb:
    plugin: nil
    stage-packages:
      - percona-server-server
      - percona-mysql-router
      - percona-xtrabackup-80
      - percona-mysql-shell
      - util-linux
    after:
      - pin-mysql-apt
  wrapper:
    plugin: dump
    source: snap/local
    prime:
      - -LICENSE
      - -NOTICE
